// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vizfolio.Infrastructure.Persistence;

#nullable disable

namespace Vizfolio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628025017_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Vizfolio.Domain.Funds.CitSubstitution", b =>
                {
                    b.Property<Guid>("CitSubstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CitName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fidelity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstituteName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstituteTicker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("_patterns")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Patterns");

                    b.HasKey("CitSubstitutionId");

                    b.HasIndex("SubstituteTicker");

                    b.ToTable("CitSubstitution", (string)null);
                });

            modelBuilder.Entity("Vizfolio.Domain.Funds.Fund", b =>
                {
                    b.Property<Guid>("FundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrantCik")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrantName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("FundId");

                    b.HasIndex("SeriesId")
                        .IsUnique();

                    b.ToTable("Fund", (string)null);
                });

            modelBuilder.Entity("Vizfolio.Domain.Funds.FundHolding", b =>
                {
                    b.Property<Guid>("FundHoldingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetCategory")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(28,4)");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FairValueUsd")
                        .HasColumnType("decimal(28,4)");

                    b.Property<Guid>("FundSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isin")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SecurityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Units")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("FundHoldingId");

                    b.HasIndex("FundSnapshotId");

                    b.HasIndex("SecurityId");

                    b.ToTable("FundHolding", (string)null);
                });

            modelBuilder.Entity("Vizfolio.Domain.Funds.FundSnapshot", b =>
                {
                    b.Property<Guid>("FundSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CashNotInPortfolioUsd")
                        .HasColumnType("decimal(28,4)");

                    b.Property<Guid>("FundId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinalFiling")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("NetAssetsUsd")
                        .HasColumnType("decimal(28,4)");

                    b.Property<string>("SourceFiling")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAssetsUsd")
                        .HasColumnType("decimal(28,4)");

                    b.Property<decimal?>("TotalLiabilitiesUsd")
                        .HasColumnType("decimal(28,4)");

                    b.HasKey("FundSnapshotId");

                    b.HasIndex("FundId", "AsOf")
                        .IsUnique();

                    b.ToTable("FundSnapshot", (string)null);
                });

            modelBuilder.Entity("Vizfolio.Domain.Portfolios.Portfolio", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("PortfolioId");

                    b.ToTable("Portfolio", (string)null);
                });

            modelBuilder.Entity("Vizfolio.Domain.Securities.Security", b =>
                {
                    b.Property<Guid>("SecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cik")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EdgarFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("_exchanges")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Exchanges");

                    b.PrimitiveCollection<string>("_tickers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Tickers");

                    b.HasKey("SecurityId");

                    b.HasIndex("Cik")
                        .IsUnique();

                    b.ToTable("Security", (string)null);
                });

            modelBuilder.Entity("Vizfolio.Domain.Funds.FundHolding", b =>
                {
                    b.HasOne("Vizfolio.Domain.Funds.FundSnapshot", null)
                        .WithMany()
                        .HasForeignKey("FundSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vizfolio.Domain.Securities.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Vizfolio.Domain.Funds.FundSnapshot", b =>
                {
                    b.HasOne("Vizfolio.Domain.Funds.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Vizfolio.Domain.Funds.MonthlyReturn", "MonthlyReturns", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ClassId")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FundSnapshotId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("Month")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("ReturnPct")
                                .HasColumnType("decimal(18,8)");

                            b1.HasKey("Id");

                            b1.HasIndex("FundSnapshotId", "Month", "ClassId");

                            b1.ToTable("FundMonthlyReturn", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FundSnapshotId");
                        });

                    b.OwnsMany("Vizfolio.Domain.Funds.ShareClass", "ShareClasses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ClassId")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("ExpenseRatio")
                                .HasColumnType("decimal(18,8)");

                            b1.Property<Guid>("FundSnapshotId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Ticker")
                                .HasMaxLength(10)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("FundSnapshotId", "ClassId")
                                .IsUnique();

                            b1.ToTable("FundShareClass", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FundSnapshotId");
                        });

                    b.Navigation("MonthlyReturns");

                    b.Navigation("ShareClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
