using Vizfolio.Domain.Reference;

namespace Vizfolio.Infrastructure.Persistence.Seed;

internal static class CountrySeed
{
    // ISO 3166-1 alpha-2 codes, plus XK (Kosovo) which is a user-assigned/transitional
    // code in widespread use across financial filings even though it is not an official
    // ISO 3166-1 assignment.
    public static IReadOnlyList<Country> All { get; } =
    [
        new("AD", "Andorra", "Europe"),
        new("AE", "United Arab Emirates", "Asia"),
        new("AF", "Afghanistan", "Asia"),
        new("AG", "Antigua and Barbuda", "Americas"),
        new("AI", "Anguilla", "Americas"),
        new("AL", "Albania", "Europe"),
        new("AM", "Armenia", "Asia"),
        new("AO", "Angola", "Africa"),
        new("AQ", "Antarctica", "Antarctic"),
        new("AR", "Argentina", "Americas"),
        new("AS", "American Samoa", "Oceania"),
        new("AT", "Austria", "Europe"),
        new("AU", "Australia", "Oceania"),
        new("AW", "Aruba", "Americas"),
        new("AX", "Åland Islands", "Europe"),
        new("AZ", "Azerbaijan", "Asia"),
        new("BA", "Bosnia and Herzegovina", "Europe"),
        new("BB", "Barbados", "Americas"),
        new("BD", "Bangladesh", "Asia"),
        new("BE", "Belgium", "Europe"),
        new("BF", "Burkina Faso", "Africa"),
        new("BG", "Bulgaria", "Europe"),
        new("BH", "Bahrain", "Asia"),
        new("BI", "Burundi", "Africa"),
        new("BJ", "Benin", "Africa"),
        new("BL", "Saint Barthélemy", "Americas"),
        new("BM", "Bermuda", "Americas"),
        new("BN", "Brunei Darussalam", "Asia"),
        new("BO", "Bolivia (Plurinational State of)", "Americas"),
        new("BQ", "Bonaire, Sint Eustatius and Saba", "Americas"),
        new("BR", "Brazil", "Americas"),
        new("BS", "Bahamas", "Americas"),
        new("BT", "Bhutan", "Asia"),
        new("BV", "Bouvet Island", "Antarctic"),
        new("BW", "Botswana", "Africa"),
        new("BY", "Belarus", "Europe"),
        new("BZ", "Belize", "Americas"),
        new("CA", "Canada", "Americas"),
        new("CC", "Cocos (Keeling) Islands", "Asia"),
        new("CD", "Congo, Democratic Republic of the", "Africa"),
        new("CF", "Central African Republic", "Africa"),
        new("CG", "Congo", "Africa"),
        new("CH", "Switzerland", "Europe"),
        new("CI", "Côte d'Ivoire", "Africa"),
        new("CK", "Cook Islands", "Oceania"),
        new("CL", "Chile", "Americas"),
        new("CM", "Cameroon", "Africa"),
        new("CN", "China", "Asia"),
        new("CO", "Colombia", "Americas"),
        new("CR", "Costa Rica", "Americas"),
        new("CU", "Cuba", "Americas"),
        new("CV", "Cabo Verde", "Africa"),
        new("CW", "Curaçao", "Americas"),
        new("CX", "Christmas Island", "Oceania"),
        new("CY", "Cyprus", "Asia"),
        new("CZ", "Czechia", "Europe"),
        new("DE", "Germany", "Europe"),
        new("DJ", "Djibouti", "Africa"),
        new("DK", "Denmark", "Europe"),
        new("DM", "Dominica", "Americas"),
        new("DO", "Dominican Republic", "Americas"),
        new("DZ", "Algeria", "Africa"),
        new("EC", "Ecuador", "Americas"),
        new("EE", "Estonia", "Europe"),
        new("EG", "Egypt", "Africa"),
        new("EH", "Western Sahara", "Africa"),
        new("ER", "Eritrea", "Africa"),
        new("ES", "Spain", "Europe"),
        new("ET", "Ethiopia", "Africa"),
        new("FI", "Finland", "Europe"),
        new("FJ", "Fiji", "Oceania"),
        new("FK", "Falkland Islands (Malvinas)", "Americas"),
        new("FM", "Micronesia, Federated States of", "Oceania"),
        new("FO", "Faroe Islands", "Europe"),
        new("FR", "France", "Europe"),
        new("GA", "Gabon", "Africa"),
        new("GB", "United Kingdom", "Europe"),
        new("GD", "Grenada", "Americas"),
        new("GE", "Georgia", "Asia"),
        new("GF", "French Guiana", "Americas"),
        new("GG", "Guernsey", "Europe"),
        new("GH", "Ghana", "Africa"),
        new("GI", "Gibraltar", "Europe"),
        new("GL", "Greenland", "Americas"),
        new("GM", "Gambia", "Africa"),
        new("GN", "Guinea", "Africa"),
        new("GP", "Guadeloupe", "Americas"),
        new("GQ", "Equatorial Guinea", "Africa"),
        new("GR", "Greece", "Europe"),
        new("GS", "South Georgia and the South Sandwich Islands", "Americas"),
        new("GT", "Guatemala", "Americas"),
        new("GU", "Guam", "Oceania"),
        new("GW", "Guinea-Bissau", "Africa"),
        new("GY", "Guyana", "Americas"),
        new("HK", "Hong Kong", "Asia"),
        new("HM", "Heard Island and McDonald Islands", "Antarctic"),
        new("HN", "Honduras", "Americas"),
        new("HR", "Croatia", "Europe"),
        new("HT", "Haiti", "Americas"),
        new("HU", "Hungary", "Europe"),
        new("ID", "Indonesia", "Asia"),
        new("IE", "Ireland", "Europe"),
        new("IL", "Israel", "Asia"),
        new("IM", "Isle of Man", "Europe"),
        new("IN", "India", "Asia"),
        new("IO", "British Indian Ocean Territory", "Asia"),
        new("IQ", "Iraq", "Asia"),
        new("IR", "Iran (Islamic Republic of)", "Asia"),
        new("IS", "Iceland", "Europe"),
        new("IT", "Italy", "Europe"),
        new("JE", "Jersey", "Europe"),
        new("JM", "Jamaica", "Americas"),
        new("JO", "Jordan", "Asia"),
        new("JP", "Japan", "Asia"),
        new("KE", "Kenya", "Africa"),
        new("KG", "Kyrgyzstan", "Asia"),
        new("KH", "Cambodia", "Asia"),
        new("KI", "Kiribati", "Oceania"),
        new("KM", "Comoros", "Africa"),
        new("KN", "Saint Kitts and Nevis", "Americas"),
        new("KP", "Korea (Democratic People's Republic of)", "Asia"),
        new("KR", "Korea, Republic of", "Asia"),
        new("KW", "Kuwait", "Asia"),
        new("KY", "Cayman Islands", "Americas"),
        new("KZ", "Kazakhstan", "Asia"),
        new("LA", "Lao People's Democratic Republic", "Asia"),
        new("LB", "Lebanon", "Asia"),
        new("LC", "Saint Lucia", "Americas"),
        new("LI", "Liechtenstein", "Europe"),
        new("LK", "Sri Lanka", "Asia"),
        new("LR", "Liberia", "Africa"),
        new("LS", "Lesotho", "Africa"),
        new("LT", "Lithuania", "Europe"),
        new("LU", "Luxembourg", "Europe"),
        new("LV", "Latvia", "Europe"),
        new("LY", "Libya", "Africa"),
        new("MA", "Morocco", "Africa"),
        new("MC", "Monaco", "Europe"),
        new("MD", "Moldova, Republic of", "Europe"),
        new("ME", "Montenegro", "Europe"),
        new("MF", "Saint Martin (French part)", "Americas"),
        new("MG", "Madagascar", "Africa"),
        new("MH", "Marshall Islands", "Oceania"),
        new("MK", "North Macedonia", "Europe"),
        new("ML", "Mali", "Africa"),
        new("MM", "Myanmar", "Asia"),
        new("MN", "Mongolia", "Asia"),
        new("MO", "Macao", "Asia"),
        new("MP", "Northern Mariana Islands", "Oceania"),
        new("MQ", "Martinique", "Americas"),
        new("MR", "Mauritania", "Africa"),
        new("MS", "Montserrat", "Americas"),
        new("MT", "Malta", "Europe"),
        new("MU", "Mauritius", "Africa"),
        new("MV", "Maldives", "Asia"),
        new("MW", "Malawi", "Africa"),
        new("MX", "Mexico", "Americas"),
        new("MY", "Malaysia", "Asia"),
        new("MZ", "Mozambique", "Africa"),
        new("NA", "Namibia", "Africa"),
        new("NC", "New Caledonia", "Oceania"),
        new("NE", "Niger", "Africa"),
        new("NF", "Norfolk Island", "Oceania"),
        new("NG", "Nigeria", "Africa"),
        new("NI", "Nicaragua", "Americas"),
        new("NL", "Netherlands", "Europe"),
        new("NO", "Norway", "Europe"),
        new("NP", "Nepal", "Asia"),
        new("NR", "Nauru", "Oceania"),
        new("NU", "Niue", "Oceania"),
        new("NZ", "New Zealand", "Oceania"),
        new("OM", "Oman", "Asia"),
        new("PA", "Panama", "Americas"),
        new("PE", "Peru", "Americas"),
        new("PF", "French Polynesia", "Oceania"),
        new("PG", "Papua New Guinea", "Oceania"),
        new("PH", "Philippines", "Asia"),
        new("PK", "Pakistan", "Asia"),
        new("PL", "Poland", "Europe"),
        new("PM", "Saint Pierre and Miquelon", "Americas"),
        new("PN", "Pitcairn", "Oceania"),
        new("PR", "Puerto Rico", "Americas"),
        new("PS", "Palestine, State of", "Asia"),
        new("PT", "Portugal", "Europe"),
        new("PW", "Palau", "Oceania"),
        new("PY", "Paraguay", "Americas"),
        new("QA", "Qatar", "Asia"),
        new("RE", "Réunion", "Africa"),
        new("RO", "Romania", "Europe"),
        new("RS", "Serbia", "Europe"),
        new("RU", "Russian Federation", "Europe"),
        new("RW", "Rwanda", "Africa"),
        new("SA", "Saudi Arabia", "Asia"),
        new("SB", "Solomon Islands", "Oceania"),
        new("SC", "Seychelles", "Africa"),
        new("SD", "Sudan", "Africa"),
        new("SE", "Sweden", "Europe"),
        new("SG", "Singapore", "Asia"),
        new("SH", "Saint Helena, Ascension and Tristan da Cunha", "Africa"),
        new("SI", "Slovenia", "Europe"),
        new("SJ", "Svalbard and Jan Mayen", "Europe"),
        new("SK", "Slovakia", "Europe"),
        new("SL", "Sierra Leone", "Africa"),
        new("SM", "San Marino", "Europe"),
        new("SN", "Senegal", "Africa"),
        new("SO", "Somalia", "Africa"),
        new("SR", "Suriname", "Americas"),
        new("SS", "South Sudan", "Africa"),
        new("ST", "Sao Tome and Principe", "Africa"),
        new("SV", "El Salvador", "Americas"),
        new("SX", "Sint Maarten (Dutch part)", "Americas"),
        new("SY", "Syrian Arab Republic", "Asia"),
        new("SZ", "Eswatini", "Africa"),
        new("TC", "Turks and Caicos Islands", "Americas"),
        new("TD", "Chad", "Africa"),
        new("TF", "French Southern Territories", "Antarctic"),
        new("TG", "Togo", "Africa"),
        new("TH", "Thailand", "Asia"),
        new("TJ", "Tajikistan", "Asia"),
        new("TK", "Tokelau", "Oceania"),
        new("TL", "Timor-Leste", "Asia"),
        new("TM", "Turkmenistan", "Asia"),
        new("TN", "Tunisia", "Africa"),
        new("TO", "Tonga", "Oceania"),
        new("TR", "Türkiye", "Asia"),
        new("TT", "Trinidad and Tobago", "Americas"),
        new("TV", "Tuvalu", "Oceania"),
        new("TW", "Taiwan, Province of China", "Asia"),
        new("TZ", "Tanzania, United Republic of", "Africa"),
        new("UA", "Ukraine", "Europe"),
        new("UG", "Uganda", "Africa"),
        new("UM", "United States Minor Outlying Islands", "Oceania"),
        new("US", "United States of America", "Americas"),
        new("UY", "Uruguay", "Americas"),
        new("UZ", "Uzbekistan", "Asia"),
        new("VA", "Holy See", "Europe"),
        new("VC", "Saint Vincent and the Grenadines", "Americas"),
        new("VE", "Venezuela (Bolivarian Republic of)", "Americas"),
        new("VG", "Virgin Islands (British)", "Americas"),
        new("VI", "Virgin Islands (U.S.)", "Americas"),
        new("VN", "Viet Nam", "Asia"),
        new("VU", "Vanuatu", "Oceania"),
        new("WF", "Wallis and Futuna", "Oceania"),
        new("WS", "Samoa", "Oceania"),
        new("XK", "Kosovo", "Europe"),
        new("YE", "Yemen", "Asia"),
        new("YT", "Mayotte", "Africa"),
        new("ZA", "South Africa", "Africa"),
        new("ZM", "Zambia", "Africa"),
        new("ZW", "Zimbabwe", "Africa"),
    ];
}
