using Vizfolio.Domain.Reference;

namespace Vizfolio.Infrastructure.Persistence.Seed;

internal static class CurrencySeed
{
    // ISO 4217 active currency codes plus precious-metal / fund / test codes (X-series).
    // MinorUnit follows ISO 4217 where defined; X-series codes that have no fractional unit
    // (metals, SDR, test codes, no-currency XXX) are recorded as 0.
    public static IReadOnlyList<Currency> All { get; } =
    [
        new("AED", "UAE Dirham", 2, null),
        new("AFN", "Afghani", 2, null),
        new("ALL", "Lek", 2, null),
        new("AMD", "Armenian Dram", 2, null),
        new("ANG", "Netherlands Antillean Guilder", 2, null),
        new("AOA", "Kwanza", 2, null),
        new("ARS", "Argentine Peso", 2, "$"),
        new("AUD", "Australian Dollar", 2, "$"),
        new("AWG", "Aruban Florin", 2, null),
        new("AZN", "Azerbaijan Manat", 2, null),
        new("BAM", "Convertible Mark", 2, null),
        new("BBD", "Barbados Dollar", 2, "$"),
        new("BDT", "Taka", 2, null),
        new("BGN", "Bulgarian Lev", 2, null),
        new("BHD", "Bahraini Dinar", 3, null),
        new("BIF", "Burundi Franc", 0, null),
        new("BMD", "Bermudian Dollar", 2, "$"),
        new("BND", "Brunei Dollar", 2, "$"),
        new("BOB", "Boliviano", 2, null),
        new("BOV", "Mvdol", 2, null),
        new("BRL", "Brazilian Real", 2, "R$"),
        new("BSD", "Bahamian Dollar", 2, "$"),
        new("BTN", "Ngultrum", 2, null),
        new("BWP", "Pula", 2, null),
        new("BYN", "Belarusian Ruble", 2, null),
        new("BZD", "Belize Dollar", 2, "$"),
        new("CAD", "Canadian Dollar", 2, "$"),
        new("CDF", "Congolese Franc", 2, null),
        new("CHE", "WIR Euro", 2, null),
        new("CHF", "Swiss Franc", 2, "Fr"),
        new("CHW", "WIR Franc", 2, null),
        new("CLF", "Unidad de Fomento", 4, null),
        new("CLP", "Chilean Peso", 0, "$"),
        new("CNY", "Yuan Renminbi", 2, "¥"),
        new("COP", "Colombian Peso", 2, "$"),
        new("COU", "Unidad de Valor Real", 2, null),
        new("CRC", "Costa Rican Colon", 2, null),
        new("CUC", "Peso Convertible", 2, null),
        new("CUP", "Cuban Peso", 2, null),
        new("CVE", "Cabo Verde Escudo", 2, null),
        new("CZK", "Czech Koruna", 2, null),
        new("DJF", "Djibouti Franc", 0, null),
        new("DKK", "Danish Krone", 2, "kr"),
        new("DOP", "Dominican Peso", 2, "$"),
        new("DZD", "Algerian Dinar", 2, null),
        new("EGP", "Egyptian Pound", 2, null),
        new("ERN", "Nakfa", 2, null),
        new("ETB", "Ethiopian Birr", 2, null),
        new("EUR", "Euro", 2, "€"),
        new("FJD", "Fiji Dollar", 2, "$"),
        new("FKP", "Falkland Islands Pound", 2, null),
        new("GBP", "Pound Sterling", 2, "£"),
        new("GEL", "Lari", 2, null),
        new("GHS", "Ghana Cedi", 2, null),
        new("GIP", "Gibraltar Pound", 2, null),
        new("GMD", "Dalasi", 2, null),
        new("GNF", "Guinean Franc", 0, null),
        new("GTQ", "Quetzal", 2, null),
        new("GYD", "Guyana Dollar", 2, "$"),
        new("HKD", "Hong Kong Dollar", 2, "$"),
        new("HNL", "Lempira", 2, null),
        new("HTG", "Gourde", 2, null),
        new("HUF", "Forint", 2, null),
        new("IDR", "Rupiah", 2, null),
        new("ILS", "New Israeli Sheqel", 2, "₪"),
        new("INR", "Indian Rupee", 2, "₹"),
        new("IQD", "Iraqi Dinar", 3, null),
        new("IRR", "Iranian Rial", 2, null),
        new("ISK", "Iceland Krona", 0, "kr"),
        new("JMD", "Jamaican Dollar", 2, "$"),
        new("JOD", "Jordanian Dinar", 3, null),
        new("JPY", "Yen", 0, "¥"),
        new("KES", "Kenyan Shilling", 2, null),
        new("KGS", "Som", 2, null),
        new("KHR", "Riel", 2, null),
        new("KMF", "Comorian Franc", 0, null),
        new("KPW", "North Korean Won", 2, null),
        new("KRW", "Won", 0, "₩"),
        new("KWD", "Kuwaiti Dinar", 3, null),
        new("KYD", "Cayman Islands Dollar", 2, "$"),
        new("KZT", "Tenge", 2, null),
        new("LAK", "Lao Kip", 2, null),
        new("LBP", "Lebanese Pound", 2, null),
        new("LKR", "Sri Lanka Rupee", 2, null),
        new("LRD", "Liberian Dollar", 2, "$"),
        new("LSL", "Loti", 2, null),
        new("LYD", "Libyan Dinar", 3, null),
        new("MAD", "Moroccan Dirham", 2, null),
        new("MDL", "Moldovan Leu", 2, null),
        new("MGA", "Malagasy Ariary", 2, null),
        new("MKD", "Denar", 2, null),
        new("MMK", "Kyat", 2, null),
        new("MNT", "Tugrik", 2, null),
        new("MOP", "Pataca", 2, null),
        new("MRU", "Ouguiya", 2, null),
        new("MUR", "Mauritius Rupee", 2, null),
        new("MVR", "Rufiyaa", 2, null),
        new("MWK", "Malawi Kwacha", 2, null),
        new("MXN", "Mexican Peso", 2, "$"),
        new("MXV", "Mexican Unidad de Inversion (UDI)", 2, null),
        new("MYR", "Malaysian Ringgit", 2, null),
        new("MZN", "Mozambique Metical", 2, null),
        new("NAD", "Namibia Dollar", 2, "$"),
        new("NGN", "Naira", 2, null),
        new("NIO", "Cordoba Oro", 2, null),
        new("NOK", "Norwegian Krone", 2, "kr"),
        new("NPR", "Nepalese Rupee", 2, null),
        new("NZD", "New Zealand Dollar", 2, "$"),
        new("OMR", "Rial Omani", 3, null),
        new("PAB", "Balboa", 2, null),
        new("PEN", "Sol", 2, null),
        new("PGK", "Kina", 2, null),
        new("PHP", "Philippine Peso", 2, "₱"),
        new("PKR", "Pakistan Rupee", 2, null),
        new("PLN", "Zloty", 2, null),
        new("PYG", "Guarani", 0, null),
        new("QAR", "Qatari Rial", 2, null),
        new("RON", "Romanian Leu", 2, null),
        new("RSD", "Serbian Dinar", 2, null),
        new("RUB", "Russian Ruble", 2, "₽"),
        new("RWF", "Rwanda Franc", 0, null),
        new("SAR", "Saudi Riyal", 2, null),
        new("SBD", "Solomon Islands Dollar", 2, "$"),
        new("SCR", "Seychelles Rupee", 2, null),
        new("SDG", "Sudanese Pound", 2, null),
        new("SEK", "Swedish Krona", 2, "kr"),
        new("SGD", "Singapore Dollar", 2, "$"),
        new("SHP", "Saint Helena Pound", 2, null),
        new("SLE", "Leone", 2, null),
        new("SLL", "Leone (pre-2022)", 2, null),
        new("SOS", "Somali Shilling", 2, null),
        new("SRD", "Surinam Dollar", 2, "$"),
        new("SSP", "South Sudanese Pound", 2, null),
        new("STN", "Dobra", 2, null),
        new("SVC", "El Salvador Colon", 2, null),
        new("SYP", "Syrian Pound", 2, null),
        new("SZL", "Lilangeni", 2, null),
        new("THB", "Baht", 2, "฿"),
        new("TJS", "Somoni", 2, null),
        new("TMT", "Turkmenistan New Manat", 2, null),
        new("TND", "Tunisian Dinar", 3, null),
        new("TOP", "Pa’anga", 2, null),
        new("TRY", "Turkish Lira", 2, "₺"),
        new("TTD", "Trinidad and Tobago Dollar", 2, "$"),
        new("TWD", "New Taiwan Dollar", 2, "$"),
        new("TZS", "Tanzanian Shilling", 2, null),
        new("UAH", "Hryvnia", 2, "₴"),
        new("UGX", "Uganda Shilling", 0, null),
        new("USD", "US Dollar", 2, "$"),
        new("USN", "US Dollar (Next day)", 2, null),
        new("UYI", "Uruguay Peso en Unidades Indexadas", 0, null),
        new("UYU", "Peso Uruguayo", 2, "$"),
        new("UYW", "Unidad Previsional", 4, null),
        new("UZS", "Uzbekistan Sum", 2, null),
        new("VED", "Bolivar Soberano (digital)", 2, null),
        new("VES", "Bolivar Soberano", 2, null),
        new("VND", "Dong", 0, "₫"),
        new("VUV", "Vatu", 0, null),
        new("WST", "Tala", 2, null),
        new("XAF", "CFA Franc BEAC", 0, null),
        new("XAG", "Silver", 0, null),
        new("XAU", "Gold", 0, null),
        new("XBA", "European Composite Unit (EURCO)", 0, null),
        new("XBB", "European Monetary Unit (E.M.U.-6)", 0, null),
        new("XBC", "European Unit of Account 9 (E.U.A.-9)", 0, null),
        new("XBD", "European Unit of Account 17 (E.U.A.-17)", 0, null),
        new("XCD", "East Caribbean Dollar", 2, "$"),
        new("XCG", "Caribbean Guilder", 2, null),
        new("XDR", "SDR (Special Drawing Right)", 0, null),
        new("XOF", "CFA Franc BCEAO", 0, null),
        new("XPD", "Palladium", 0, null),
        new("XPF", "CFP Franc", 0, null),
        new("XPT", "Platinum", 0, null),
        new("XSU", "Sucre", 0, null),
        new("XTS", "Codes specifically reserved for testing purposes", 0, null),
        new("XUA", "ADB Unit of Account", 0, null),
        new("XXX", "No currency / transactions in no currency", 0, null),
        new("YER", "Yemeni Rial", 2, null),
        new("ZAR", "Rand", 2, "R"),
        new("ZMW", "Zambian Kwacha", 2, null),
        new("ZWG", "Zimbabwe Gold", 2, null),
        new("ZWL", "Zimbabwe Dollar (pre-2024)", 2, null),
    ];
}
